import styled from "@emotion/styled";
import Head from "next/head";
import { FC, ReactNode } from "react";

interface MainContainerProps {
  children: ReactNode;
}

const StyledMainContainer = styled.div`
  width: 100%;
  height: 100vh;
`;

const MainContainer: FC<MainContainerProps> = ({ children }) => {
  return (
    <StyledMainContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </StyledMainContainer>
  );
};

export default MainContainer;
